# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfl" do
  version "1.3.104"

  on_macos do
    on_arm do
      sha256 "26d03a1245ea07eb774ae49267a3c0a95c9d29c3c83442e15087346a06eba64e"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa19c702037891872f414e3ecc8e9c706e81c57b90bf19e5233ee0564b992264"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0a480961a12d014951c21f39f82eaebabb03f6714b3071787502345f2879efee"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4cb7d86d02a5ea867a8394642559bf090104353081785aec4e3a45e0f2fda0fb"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cfl"
  desc "Command-line interface for Atlassian Confluence"
  homepage "https://github.com/open-cli-collective/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfl"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/cfl"]
  end

  # No zap stanza required

  caveats <<~EOS
    cfl has been installed. Run 'cfl init' to configure.
  EOS
end
