# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfl" do
  name "cfl"
  desc "Command-line interface for Atlassian Confluence"
  homepage "https://github.com/open-cli-collective/atlassian-cli"
  version "1.0.24"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfl"

  on_macos do
    on_intel do
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_darwin_amd64.tar.gz"
      sha256 "34f79320080162ca63cda397758cb0940e23410ba245eb6b9666f04b25b04ae5"
    end
    on_arm do
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_darwin_arm64.tar.gz"
      sha256 "47acc9aae17446997f028586afaefac2bc7e9051b40984f21927ebe21585a36e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_linux_amd64.tar.gz"
      sha256 "935ee931f733e01ef3f9d5d68309cea9bf729e653a4b088451f874777b8b39c1"
    end
    on_arm do
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_linux_arm64.tar.gz"
      sha256 "9d456b5c7350182a21a9ee7be3dd3c8fea492dfeab335dbcd10c04e69ce1ffc8"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cfl"]
  end

  caveats do
    "cfl has been installed. Run 'cfl init' to configure."
  end

  # No zap stanza required
end
