# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfl" do
  version "1.0.43"

  on_macos do
    on_intel do
      sha256 "2458e2c1dd8cd5a95327cbc4a5ab7cccb985fc8187644c1d4dac2d14c8e4d1fa"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e962f4262361ae8373b7db3c99301998f0ea3b057b7c508e3fe22810e94429d"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "868f78f09bfc6544f3fc39bd5c19f60e23c178b6090d0e71e52f06a4fd1a8127"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c297615ac9c6cf2eb96db9fa0ef7932abb1bf17c7572df231ba95eb3e34c1532"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/cfl-v#{version}/cfl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cfl"
  desc "Command-line interface for Atlassian Confluence"
  homepage "https://github.com/open-cli-collective/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfl"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cfl"]
  end

  # No zap stanza required

  caveats <<~EOS
    cfl has been installed. Run 'cfl init' to configure.
  EOS
end
