# This file was generated by GoReleaser. DO NOT EDIT.
cask "codereview-cli" do
  version "0.10.200"

  on_macos do
    on_intel do
      sha256 "caa0ac96c86ff8df04dc260185298f18cc9a75ea7f054fb3b784f5a52692df97"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e8cca44349f9c8632b2073b625d6fdd8ca2906cd7d01a3ede41a5e5ded52ffb"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dfd5d34d2226a0399c7068d0f68a0b934f36c651f81e97d1eeaff183a98ac735"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca7891aa6c9abeb8a73359a17c5302bf19167195f94ea9dd21754028c95e0a02"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "codereview-cli"
  desc "Automated pull-request review CLI"
  homepage "https://github.com/open-cli-collective/codereview-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cr"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cr"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure cr, follow the setup examples in the README:
      https://github.com/open-cli-collective/codereview-cli#authentication-and-setup

    Secrets are stored in the OS credential store. They are never written to
    config.yml.
  EOS
end
