# This file was generated by GoReleaser. DO NOT EDIT.
cask "codereview-cli" do
  version "0.3.153"

  on_macos do
    on_intel do
      sha256 "92dc6dfef7c139eaeb1299d6f15cfd7fd616b40965de5eb5f5e027d0d880fe6b"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6c56c41ee04f375839d3fd495dd4af74e3047f6da80122a3f43fb4547c8c1277"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cf26b3e6845042d6b75ba0a9399374bcb6e672ebc07f6597bf4630a58fdfd655"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cecda7219da833676b7a08a2f7122c994fd9f22f259be4259a9e468fd22e4e23"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "codereview-cli"
  desc "Automated pull-request review CLI"
  homepage "https://github.com/open-cli-collective/codereview-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cr"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cr"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure cr, follow the setup examples in the README:
      https://github.com/open-cli-collective/codereview-cli#authentication-and-setup

    Secrets are stored in the OS credential store. They are never written to
    config.yml.
  EOS
end
