# This file was generated by GoReleaser. DO NOT EDIT.
cask "codereview-cli" do
  version "0.10.304"

  on_macos do
    on_arm do
      sha256 "47cae385dee1d831bf3e3b9c33c95e077537117366a635b728c8eb2213af3374"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "857d57251bcdb9ce33a2bab106f8e66b515de63c173adc69bea55450be7c4d13"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "295d24c17a9b27b1eb4b1ff621d1654136a2957a58c5f3940fbc56388bcbbdff"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c369954d4b2e42778b545cbdd97925c337bd5ad31e7797536bd951413e62faf8"
      url "https://github.com/open-cli-collective/codereview-cli/releases/download/v#{version}/cr_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "codereview-cli"
  desc "Automated pull-request review CLI"
  homepage "https://github.com/open-cli-collective/codereview-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cr"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cr"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure cr, follow the setup examples in the README:
      https://github.com/open-cli-collective/codereview-cli#authentication-and-setup

    Secrets are stored in the OS credential store. They are never written to
    config.yml.
  EOS
end
