# This file was generated by GoReleaser. DO NOT EDIT.
cask "cpm" do
  version "0.3.3"

  on_macos do
    sha256 "77a9c790ed4cc5345ad7b4fbac6e9c3736ef795e562ba8ad256dbd30fc306afd"
    url "https://github.com/open-cli-collective/cpm/releases/download/v#{version}/cpm_#{version}_darwin_universal.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "d569c77025a382b7ce94811cebf8102b7c5853f103effaaafd42da3c14181c61"
      url "https://github.com/open-cli-collective/cpm/releases/download/v#{version}/cpm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "71613aa8a746872009211487e2557e80faa05b2aa3e3f34dcc5bf5dfc3970dad"
      url "https://github.com/open-cli-collective/cpm/releases/download/v#{version}/cpm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cpm"
  desc "TUI for managing Claude Code plugins"
  homepage "https://github.com/open-cli-collective/cpm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cpm"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cpm"]
  end

  # No zap stanza required

  caveats <<~EOS
    cpm has been installed. Run 'cpm --help' for usage.
  EOS
end
