# This file was generated by GoReleaser. DO NOT EDIT.
cask "cpm" do
  name "cpm"
  desc "TUI for managing Claude Code plugins"
  homepage "https://github.com/open-cli-collective/cpm"
  version "0.2.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cpm"

  on_macos do
    on_intel do
      url "https://github.com/open-cli-collective/cpm/releases/download/v#{version}/cpm_#{version}_darwin_amd64.tar.gz"
      sha256 "1ff10befcc2a66133b1066f987d3d73e1f2b76f4efb706bf7c1b76b95e24d771"
    end
    on_arm do
      url "https://github.com/open-cli-collective/cpm/releases/download/v#{version}/cpm_#{version}_darwin_arm64.tar.gz"
      sha256 "d7f8c809bd1ddebfd253c4f3c6f94cce0fe5ad2702b9c650eb9206b1bb7383d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/open-cli-collective/cpm/releases/download/v#{version}/cpm_#{version}_linux_amd64.tar.gz"
      sha256 "87e082f8077d0c631d2966a32a194854ea7533a6d901e9e1aef37e7cf888673b"
    end
    on_arm do
      url "https://github.com/open-cli-collective/cpm/releases/download/v#{version}/cpm_#{version}_linux_arm64.tar.gz"
      sha256 "619aa0b87a9e0f3cc36b7b3c4ab134311da95e1b27ab32e66ad7f3ac38489fa7"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cpm"]
  end

  caveats do
    "cpm has been installed. Run 'cpm --help' for usage."
  end

  # No zap stanza required
end
