# This file was generated by GoReleaser. DO NOT EDIT.
cask "cpm" do
  name "cpm"
  desc "TUI for managing Claude Code plugins"
  homepage "https://github.com/open-cli-collective/cpm"
  version "0.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cpm"

  on_macos do
    on_intel do
      url "https://github.com/open-cli-collective/cpm/releases/download/v#{version}/cpm_#{version}_darwin_amd64.tar.gz"
      sha256 "4b75016f41b0f962ea769a7fc6d1eb9f5ffbe4ba1c90eb9971c89c2c10e425a8"
    end
    on_arm do
      url "https://github.com/open-cli-collective/cpm/releases/download/v#{version}/cpm_#{version}_darwin_arm64.tar.gz"
      sha256 "502195aa1b0c810a88ba54df7aa63fa60d3bc4b1fac8fc2eda743a3ffa266e24"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/open-cli-collective/cpm/releases/download/v#{version}/cpm_#{version}_linux_amd64.tar.gz"
      sha256 "c1d08cbdc152edae3e5a228ea05c7c9af5f8d557defa02f79f209b5fb267582c"
    end
    on_arm do
      url "https://github.com/open-cli-collective/cpm/releases/download/v#{version}/cpm_#{version}_linux_arm64.tar.gz"
      sha256 "a94cf5e0b43fa230ea2a2e5ae947edb86932247bd948d19bc909c77c0a504194"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cpm"]
  end

  caveats do
    "cpm has been installed. Run 'cpm --help' for usage."
  end

  # No zap stanza required
end
