# This file was generated by GoReleaser. DO NOT EDIT.
cask "google-readwrite" do
  version "1.2.1"

  on_macos do
    on_arm do
      sha256 "f99b9dd80673b19cb07b43350e4bcd72901bc0abc51b1c8594df6adc4494ecaa"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "db6febafd5465a1823b02fb3bb90160015bac2a7c4047526481b2555ece3ceba"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "858a9d3d8dc679f8ec09f9e209c394483d509bf6ba088fa9295419e6971a8795"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ba0aa03c744dbcc4bfcc77fecd41117be5c282a9965603168ad587bf2087b6a"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "grw"
  desc "Read-write command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grw"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grw"]
  end

  # No zap stanza required

  caveats <<~EOS
    grw has been installed. Run 'grw init' to configure.
    On macOS, your token is stored securely in the system Keychain.
  EOS
end
