# This file was generated by GoReleaser. DO NOT EDIT.
cask "google-readonly" do
  name "google-readonly"
  desc "Read-only command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-readonly"
  version "1.0.38"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gro"

  on_macos do
    on_intel do
      url "https://github.com/open-cli-collective/google-readonly/releases/download/v#{version}/gro_v#{version}_darwin_amd64.tar.gz"
      sha256 "a688abd7dfa84b31a84e7e9e22adf17b3a349975d4e5eccab4893cd7aa8aa5c2"
    end
    on_arm do
      url "https://github.com/open-cli-collective/google-readonly/releases/download/v#{version}/gro_v#{version}_darwin_arm64.tar.gz"
      sha256 "922da456421926357b84afc95a5d4d6bf411389791abfbb1278dede5be202ec2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/open-cli-collective/google-readonly/releases/download/v#{version}/gro_v#{version}_linux_amd64.tar.gz"
      sha256 "ca5fcffca24642e3c0ce878cb9f729b7a138eb9992737d1293912f1cf6b5f48f"
    end
    on_arm do
      url "https://github.com/open-cli-collective/google-readonly/releases/download/v#{version}/gro_v#{version}_linux_arm64.tar.gz"
      sha256 "df1d7002980e4b9ebaed871b05bde12233ada3275e51db60e6528198d533a4fe"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gro"]
  end

  caveats do
    "gro has been installed. Run 'gro init' to configure."
    "On macOS, your token is stored securely in the system Keychain."
  end

  # No zap stanza required
end
