# This file was generated by GoReleaser. DO NOT EDIT.
cask "google-readonly" do
  version "1.0.40"

  on_macos do
    on_intel do
      sha256 "89cef9cacb20996ebf24cce1f6c005b20d3958bd2f2cacb7f8dc45c0d01768c0"
      url "https://github.com/open-cli-collective/google-readonly/releases/download/v#{version}/gro_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "70fc18edb9bddc4dba77319cbddaecf164f921dba0597098c9e429dc7e3eccee"
      url "https://github.com/open-cli-collective/google-readonly/releases/download/v#{version}/gro_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a270293ff781cd965a075036ad0debf4ff551bbf84929f57cdd1af6ceb0dbf3"
      url "https://github.com/open-cli-collective/google-readonly/releases/download/v#{version}/gro_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be9f233942d9a7971af9cfda87ee2385c45eba0a7a88221aa73cd74c8cc50e08"
      url "https://github.com/open-cli-collective/google-readonly/releases/download/v#{version}/gro_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "google-readonly"
  desc "Read-only command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-readonly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gro"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gro"]
  end

  # No zap stanza required

  caveats <<~EOS
    gro has been installed. Run 'gro init' to configure.
    On macOS, your token is stored securely in the system Keychain.
  EOS
end
