# This file was generated by GoReleaser. DO NOT EDIT.
cask "google-readonly" do
  version "1.2.7"

  on_macos do
    on_arm do
      sha256 "8a296d437245db71d59baed3902b5b657e57e3e4938a59da6dacf621abb1ccbc"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "19dc7aec78f1607acc28706821c841635914c11e1eb5bfeaf8036cec418016b0"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d890a80e8b4c1ad763d049b58ef28363d34f27e44eecde92e27c073269f131af"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f7232de1e0d37d229bd108ebc8c31e9014e468edb0a7094b05f842d02fb51182"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "gro"
  desc "Read-only command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gro"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gro"]
  end

  # No zap stanza required

  caveats <<~EOS
    gro has been installed. Run 'gro init' to configure.
    On macOS, your token is stored securely in the system Keychain.
  EOS
end
