# This file was generated by GoReleaser. DO NOT EDIT.
cask "google-readwrite" do
  version "1.2.7"

  on_macos do
    on_arm do
      sha256 "18b2c0253396a8d8ff607a6c3736957cfa30381894c5834408db08e03dffab1f"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c24a0baeb897679eebcdd4afaf75b68a72628aada7f3ebf5078d3b3752e4cf0b"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "213217f25667fb4c220e82db2d3c09ea7ffa373f9a8b13628f6f0f3809d57721"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f0efc9c66920b92a8212a5f9e6d75995db7d0e947719f06c30b57605e4f96c6"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "grw"
  desc "Read-write command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grw"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grw"]
  end

  # No zap stanza required

  caveats <<~EOS
    grw has been installed. Run 'grw init' to configure.
    On macOS, your token is stored securely in the system Keychain.
  EOS
end
