# This file was generated by GoReleaser. DO NOT EDIT.
cask "google-readwrite" do
  version "1.2.5"

  on_macos do
    on_arm do
      sha256 "57b4acdbc017ffc107312c361bc4b1a63114be4f6e0d5a32a9f220d24eb96805"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bf4aaf4bf04a6eb75942027519d286a5df85ba00b0245d4090d4cab834e91524"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "47e4ba5552c80cc12eb14dd06b14eba754a32fbb26306f90a6ceed6e564f5474"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f05a0c880e0f6fa1bc735f53efad1d5689857b941cddb7c814a1fd79f03e548a"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "grw"
  desc "Read-write command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grw"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grw"]
  end

  # No zap stanza required

  caveats <<~EOS
    grw has been installed. Run 'grw init' to configure.
    On macOS, your token is stored securely in the system Keychain.
  EOS
end
