# This file was generated by GoReleaser. DO NOT EDIT.
cask "gro" do
  version "2.0.12"

  on_macos do
    on_arm do
      sha256 "56392e589b5e5fba0272c1723cf710e675f28bef83de8368db6cf40461bbc9e7"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6fce9af5713cc35dd97987340553e23e22b599a0456f720af3fb241b94f4c46d"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d31319c6476bbbf77e1fd98c35d4380c4f8c39723478474d297420316d426382"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "60dcef58b5768613bfcae84ad64b29b2a703248c7aa450f26f0cc58f0c299c7b"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "gro"
  desc "Read-only command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gro"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gro"]
  end

  # No zap stanza required

  caveats <<~EOS
    gro has been installed. Run 'gro init' to configure.
    On macOS, your token is stored securely in the system Keychain.
  EOS
end
