# This file was generated by GoReleaser. DO NOT EDIT.
cask "gro" do
  version "1.2.2"

  on_macos do
    on_arm do
      sha256 "a0c6d03c9f1c99b533f4829d7a45e3aedaa75538a2b10a0524288e574fbbd54b"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e40386898703df5846cbe746006a610ccf93abd26ab853f13d94ebadec05c267"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "37dc2d955cfea983874f247e6f548f88b9cecc6810cfefa35611da762331df5f"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "87d99ef35c4b9904e17a01e9e6bbdca27a045361081e0aa4dc170d1646c2a2f0"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "gro"
  desc "Read-only command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gro"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gro"]
  end

  # No zap stanza required

  caveats <<~EOS
    gro has been installed. Run 'gro init' to configure.
    On macOS, your token is stored securely in the system Keychain.
  EOS
end
