# This file was generated by GoReleaser. DO NOT EDIT.
cask "gro" do
  version "2.0.11"

  on_macos do
    on_arm do
      sha256 "9c3e9e2153d66ceedaaac05fd104234e8fa7b99161236761b3c03ae19c270dfb"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d9c367385b3ad67edb862b8c46b1ffcb1e0de36b2fbb0df1c0a5105bc9daf066"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "63e4115f880124c7ce4609e23e1cb87a3e83a77e3d2631400bc8bbfde4b92a8e"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e0adb1b37dbf1e57f00a8800202be1fb7b019ba8bbaaffeda4852af19d6cfbd1"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/gro_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "gro"
  desc "Read-only command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gro"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "gro"], base: :staged_path
  end

  # No zap stanza required

  caveats <<~EOS
    gro has been installed. Run 'gro init' to configure.
    On macOS, your token is stored securely in the system Keychain.
  EOS
end
