# This file was generated by GoReleaser. DO NOT EDIT.
cask "grw" do
  version "2.0.12"

  on_macos do
    on_arm do
      sha256 "fe99b70964e7c1dec041eb6deae8327d68667d183c9415f647a8ad2e40d7ba4f"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "23f67d8dedadfaa8e9b44075b76d90643814ee9f7919ff698dc2666442ed78b3"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f8822d746726a8c417d4a2105aa4843ae54f4a4cc577d6c94ca9e223c02022b7"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "075a53a744f896242d27f8b1c84b986a5cd79c001f2c8aac1afdb5dbd2776ea4"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "grw"
  desc "Read-write command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grw"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "grw"], base: :staged_path
  end

  # No zap stanza required

  caveats <<~EOS
    grw has been installed. Run 'grw init' to configure.
    On macOS, your token is stored securely in the system Keychain.
  EOS
end
