# This file was generated by GoReleaser. DO NOT EDIT.
cask "grw" do
  version "2.0.13"

  on_macos do
    on_arm do
      sha256 "1ce36f4c663f7bb95c01fee3b7b54d70919dc7ce72f4822f0537ccac812cee43"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd09c33b7bf3755266b961f044c72c8c7d5da92770ebd3b129d7e80a89a6ae2e"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "07e7a2441f572132f58e1fb2585de064f02f590d8bec042990cd8ecd2ca316af"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "20965853207bfbbebc2f6dc2211c5640f66c51337f6b568ab84848b386f8c931"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "grw"
  desc "Read-write command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grw"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/grw"]
  end

  # No zap stanza required

  caveats <<~EOS
    grw has been installed. Run 'grw init' to configure.
    On macOS, your token is stored securely in the system Keychain.
  EOS
end
