# This file was generated by GoReleaser. DO NOT EDIT.
cask "grw" do
  version "1.2.2"

  on_macos do
    on_arm do
      sha256 "d89a81fd4e53cee6dd261b4a995663292acffacbe21902da8454004749ee898a"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5aefb88d9a29bafa9ddc59670141d49e904d39b593634e5e13ce3e2d564421ba"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5a32ba359581eb63111e24d29d8b9f45348e801602f1b9110ccc34a61622dc10"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "abe96b216033a05114a40bca517ee8b60cc199715913b4f46defcf154bed9cc2"
      url "https://github.com/open-cli-collective/google-cli/releases/download/v#{version}/grw_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "grw"
  desc "Read-write command-line interface for Google services"
  homepage "https://github.com/open-cli-collective/google-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grw"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grw"]
  end

  # No zap stanza required

  caveats <<~EOS
    grw has been installed. Run 'grw init' to configure.
    On macOS, your token is stored securely in the system Keychain.
  EOS
end
