# This file was generated by GoReleaser. DO NOT EDIT.
cask "hubspot-cli" do
  version "0.1.21"

  on_macos do
    on_intel do
      sha256 "aa9fccb84e8bbf17c13574c9b187553a114df576ea0aacd39697be5364485a73"
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e3ca76a2e68feb390f954a9e2eacb2a953cd78ea84d2c3661081dafd4065126"
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d55d7bc81dc67136033abe7f0f7d4e0c39bbc8d5d79d40600b5a93c3e26e5cb5"
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "518c17091acae934a74bb731fbfca181fe1841c827c53cfb00cfa1cb702a6dca"
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hubspot-cli"
  desc "Command-line interface for HubSpot"
  homepage "https://github.com/open-cli-collective/hubspot-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hubspot-cli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hspt"]
  end

  # No zap stanza required

  caveats <<~EOS
    hubspot-cli has been installed.

    To configure, run:
      hspt init

    Get your API token from your HubSpot account settings.
  EOS
end
