# This file was generated by GoReleaser. DO NOT EDIT.
cask "hubspot-cli" do
  name "hubspot-cli"
  desc "Command-line interface for HubSpot"
  homepage "https://github.com/open-cli-collective/hubspot-cli"
  version "0.1.20"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hubspot-cli"

  on_macos do
    on_intel do
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_darwin_amd64.tar.gz"
      sha256 "bf56602e674f3c75677422eff6081ed7c78b5144b4237bf5b2fef277125c5b74"
    end
    on_arm do
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_darwin_arm64.tar.gz"
      sha256 "e7b5f026bb0945b2e8c127bad49a25a40e501ebcb86674cfb8aef9d02aa9b5d4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_linux_amd64.tar.gz"
      sha256 "6ee82d600aeb4098283c7f4a496d6f72b7d00ca3da804234f4394bda648694d7"
    end
    on_arm do
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_linux_arm64.tar.gz"
      sha256 "5a0afab0a2d4d2cf5819a87b79d29aa3faa36ed163a853a69968d6be280d48c9"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hspt"]
  end

  caveats do
    "hubspot-cli has been installed."
    ""
    "To configure, run:"
    "  hspt init"
    ""
    "Get your API token from your HubSpot account settings."
  end

  # No zap stanza required
end
