# This file was generated by GoReleaser. DO NOT EDIT.
cask "hubspot-cli" do
  version "0.1.23"

  on_macos do
    on_intel do
      sha256 "9ac4100a2494bad5d3c190760264f49af0cb3a2e0d9a81f6a95778b0f478397a"
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "13178f5da6836c7a47663b40a5ccdc75c500c64d1276e56cece0ad20a168303f"
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca04cc7fce4fce93a758a588675d393c3f6909e59667fc9d6d3f84f386b0951a"
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bdfc3bf82b1c4a0aa2e4cf9a664fc24479d059171b2fd4026d72ead314ab7c16"
      url "https://github.com/open-cli-collective/hubspot-cli/releases/download/v#{version}/hspt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hubspot-cli"
  desc "Command-line interface for HubSpot"
  homepage "https://github.com/open-cli-collective/hubspot-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hspt"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hspt"]
  end

  # No zap stanza required

  caveats <<~EOS
    hubspot-cli has been installed.

    To configure, run:
      hspt init

    Get your API token from your HubSpot account settings.
  EOS
end
