# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-ticket-cli" do
  version "1.0.103"

  on_macos do
    on_intel do
      sha256 "7a651b1b29367b91f55f1185f246f0f9b8ceffec931e60e65f011e4cd54869f9"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8319928a589eb1b353ee8d648a29590a072b4efc1389048e1f83789425365e1"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ea79d838a7959efd67fc4745fda7707b6043601fded201a201d404f17fc03fd7"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a86050b8841b45935425da5a09c2dea749805e47d60205617c20b21b0bc2fe7c"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jira-ticket-cli"
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/open-cli-collective/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtk"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jtk"]
  end

  # No zap stanza required

  caveats <<~EOS
    jtk has been installed.

    To configure, run:
      jtk config set --domain DOMAIN --email EMAIL --token TOKEN

    Get your API token from: https://id.atlassian.com/manage-profile/security/api-tokens
  EOS
end
