# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-ticket-cli" do
  version "1.0.77"

  on_macos do
    on_intel do
      sha256 "1864e9ecf5f0380a5d7bbe9daf592dda050254278cf077b487473473208bede6"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa62a5199eb373760856423707e57256464a23b63e7654f174959338fb209b92"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec29eca6cabd33913194df9ecb8458e8ab182f76314880d8522bcc4485ba0589"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "52c9feb3ca50859f73ce48f0b15ba7060485c11ce62ecf98e0422a432a7f9e82"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jira-ticket-cli"
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/open-cli-collective/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtk"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jtk"]
  end

  # No zap stanza required

  caveats <<~EOS
    jtk has been installed.

    To configure, run:
      jtk config set --domain DOMAIN --email EMAIL --token TOKEN

    Get your API token from: https://id.atlassian.com/manage-profile/security/api-tokens
  EOS
end
