# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-ticket-cli" do
  version "1.0.71"

  on_macos do
    on_intel do
      sha256 "791650cafa2df12a64b1c9e9e9581a1b5fe12f31bd2c9c69797262331812c687"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "699825a7ba9b22130d6029069e82649d6b57b236f96b0c29c37dc198b269e579"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ccac8486eeb648d0a5e88fd794ffe361c9ae486eb705b89932831e52416e8ad8"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "22a49b6d512eba44ca36b3743dfe8646ddd433071b91f5ff4327dc8a60bb4dac"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jira-ticket-cli"
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/open-cli-collective/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtk"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jtk"]
  end

  # No zap stanza required

  caveats <<~EOS
    jtk has been installed.

    To configure, run:
      jtk config set --domain DOMAIN --email EMAIL --token TOKEN

    Get your API token from: https://id.atlassian.com/manage-profile/security/api-tokens
  EOS
end
