# This file was generated by GoReleaser. DO NOT EDIT.
cask "jtk" do
  name "jtk"
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/open-cli-collective/atlassian-cli"
  version "1.0.46"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtk"

  on_macos do
    on_intel do
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_amd64.tar.gz"
      sha256 "f6468213a821f7c03524933826632feeaeac9a4979283215665adfa213124d21"
    end
    on_arm do
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_arm64.tar.gz"
      sha256 "1075c04a4f831c39778268779371a4af77c3e2395ea6de98d46e41c1d0506031"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_amd64.tar.gz"
      sha256 "60c0424b4b7359e6d156605e13c146c9d28091573d363d777c40c2e2068dc046"
    end
    on_arm do
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_arm64.tar.gz"
      sha256 "c9f2e2c4ee42b44c431ea6a86a2daa5ccc1478ec8f63b3a858566b61b1d55e82"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jtk"]
  end

  caveats do
    "jtk has been installed."
    ""
    "To configure, run:"
    "  jtk config set --domain DOMAIN --email EMAIL --token TOKEN"
    ""
    "Get your API token from: https://id.atlassian.com/manage-profile/security/api-tokens"
  end

  # No zap stanza required
end
