# This file was generated by GoReleaser. DO NOT EDIT.
cask "jtk" do
  version "1.0.108"

  on_macos do
    on_intel do
      sha256 "358a2ea3300194c1ada2e303378b31881fc24a2f514cabf0f12f3ffe2b751bd2"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "33d0eb3fa38cab816702a3e429adfa979db0042fafaeaafafeff8abc546b516f"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "876f09ac49bb42538fd24dff20b1233a52b1a0eace9b3035da0bc0f749304548"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f6f577753062625e26f30b4d902b19c6d214ceae7ff52cea46472a51c48f57f"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jtk"
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/open-cli-collective/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtk"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jtk"]
  end

  # No zap stanza required

  caveats <<~EOS
    jtk has been installed.

    To configure, run:
      jtk config set --domain DOMAIN --email EMAIL --token TOKEN

    Get your API token from: https://id.atlassian.com/manage-profile/security/api-tokens
  EOS
end
