# This file was generated by GoReleaser. DO NOT EDIT.
cask "jtk" do
  version "1.3.175"

  on_macos do
    on_arm do
      sha256 "5201aa144731fd5fe7d5d5b3899d04841f08ce840d73379fadabf8ac759fe351"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "585fe654edbcc1b7dd5c6a170f2d18b551227cd28972575d09d820da55717632"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f2177948997199cd89b1884e411821a2230fd59fa4e35bf0433d00fd3b3f8fe6"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8c801aaaa2678ec235b52be90f0c4e6ccedc5a94c258cf8cec74d3b6724dc0c3"
      url "https://github.com/open-cli-collective/atlassian-cli/releases/download/jtk-v#{version}/jtk_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jtk"
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/open-cli-collective/atlassian-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jtk"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/jtk"]
  end

  # No zap stanza required

  caveats <<~EOS
    jtk has been installed.

    To configure, run:
      jtk config set --domain DOMAIN --email EMAIL --token TOKEN

    Get your API token from: https://id.atlassian.com/manage-profile/security/api-tokens
  EOS
end
