# This file was generated by GoReleaser. DO NOT EDIT.
cask "newrelic-cli" do
  version "1.1.50"

  on_macos do
    on_intel do
      sha256 "a791c329dc9ff443a4eb0b06044c549a0605f973ce3e8c7c5cd41a83d80cc932"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8607b99bd8ca05b87e4e1b81cb7483ad634621d9e325a58bf53fb0efa8c8d33"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "01f01246e0f39a2ff7069e2cf8b218043a8b64ec527702c022924d252b095d55"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "25356ad583e7ad2f29ef23ecf3c40fa9267f2948335ec344a832033e90b71849"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "nrq"
  desc "Command-line interface for New Relic"
  homepage "https://github.com/open-cli-collective/newrelic-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nrq"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nrq"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure nrq, run:
      nrq init

    Your API key is stored in the OS keyring (Keychain on macOS,
    Credential Manager on Windows, Secret Service on Linux).
    It is never written to a plaintext file.
  EOS
end
