# This file was generated by GoReleaser. DO NOT EDIT.
cask "nrq" do
  version "1.1.55"

  on_macos do
    on_intel do
      sha256 "2712405fc6971ded427d74e2d7782b3b71fdbc619dea9e86f28dfcedd55b1ec7"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e9995526f9a37bb5b7a279d860dd6c5237c63868b7b0a6331b0f7526b73363c7"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "201c4accdb67b803b6f9d7be53577c4f892b360dae29c0a2742186ec1a0f4602"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "55c42ba90ec73f6758d39b1b46ddc079fd8ffa050f14b4e969003b1af0f7e85e"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "nrq"
  desc "Command-line interface for New Relic"
  homepage "https://github.com/open-cli-collective/newrelic-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nrq"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nrq"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure nrq, run:
      nrq init

    Your API key is stored in the OS keyring (Keychain on macOS,
    Credential Manager on Windows, Secret Service on Linux).
    It is never written to a plaintext file.
  EOS
end
