# This file was generated by GoReleaser. DO NOT EDIT.
cask "nrq" do
  version "1.1.58"

  on_macos do
    on_arm do
      sha256 "7ead2905912c05f40aa6a6d38f965b4739a12ff8883510be2f45ab21a7b77974"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9714c9c9da01a27855745bb2ce86c971b316baca14b8eb139e93f13d018871a0"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "253fc429eab3dff9372083a05a6815052d9ec4521cc1005832728b4759eeccfb"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d530540c8d4c8e33b837711eaaf1652a61284a9d6156c8c13f159b136f5d2b6"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "nrq"
  desc "Command-line interface for New Relic"
  homepage "https://github.com/open-cli-collective/newrelic-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nrq"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/nrq"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure nrq, run:
      nrq init

    Your API key is stored in the OS keyring (Keychain on macOS,
    Credential Manager on Windows, Secret Service on Linux).
    It is never written to a plaintext file.
  EOS
end
