# This file was generated by GoReleaser. DO NOT EDIT.
cask "nrq" do
  version "1.1.57"

  on_macos do
    on_intel do
      sha256 "ef3e29d10b94dfb71582c68bd2c5e57b445627e63eadb47e55e376f369cf5019"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d9abf44e50caa63478c66be9e97a1c575e6beb38be749ed86ad83148596f2d38"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b2ae3f69d73ace4738d881ff1e208f1e762c00ba7b9a7aeaa525bff154c9493d"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bda43f030c834eaed0a7a922231f50de0eea014d779360223bdd5dd4d77c475f"
      url "https://github.com/open-cli-collective/newrelic-cli/releases/download/v#{version}/nrq_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "nrq"
  desc "Command-line interface for New Relic"
  homepage "https://github.com/open-cli-collective/newrelic-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nrq"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nrq"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure nrq, run:
      nrq init

    Your API key is stored in the OS keyring (Keychain on macOS,
    Credential Manager on Windows, Secret Service on Linux).
    It is never written to a plaintext file.
  EOS
end
