# This file was generated by GoReleaser. DO NOT EDIT.
cask "salesforce-cli" do
  name "salesforce-cli"
  desc "Command-line interface for Salesforce"
  homepage "https://github.com/open-cli-collective/salesforce-cli"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sfdc"

  on_macos do
    on_intel do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_darwin_amd64.tar.gz"
      sha256 "89f26eead73007bc23cda4658212d6c71e4885a4397b6c2ff81131272b37cb31"
    end
    on_arm do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_darwin_arm64.tar.gz"
      sha256 "d69ceab540b08f8b507c4d50878786441b9702151383cb5466ba8c069ade9fa4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_linux_amd64.tar.gz"
      sha256 "01ce7d088bd30b570c331cbfd5fb1c25cb25124de97aa57d0cca953c6a60cd59"
    end
    on_arm do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_linux_arm64.tar.gz"
      sha256 "d6711d0a8c566e8025cc80d1f180ae5a92567f836adc49370f6b7d7c4f58b406"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sfdc"]
  end

  caveats do
    "salesforce-cli has been installed."
    ""
    "To configure, run:"
    "  sfdc init"
    ""
    "You'll need a Connected App in Salesforce with OAuth 2.0 enabled."
  end

  # No zap stanza required
end
