# This file was generated by GoReleaser. DO NOT EDIT.
cask "salesforce-cli" do
  name "salesforce-cli"
  desc "Command-line interface for Salesforce"
  homepage "https://github.com/open-cli-collective/salesforce-cli"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sfdc"

  on_macos do
    on_intel do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_darwin_amd64.tar.gz"
      sha256 "a4f2b801d29075ee6a94c6b6afb5a97a9f841f1ea4a0821830b02c73dc6f410d"
    end
    on_arm do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_darwin_arm64.tar.gz"
      sha256 "1c59eb25f0cb06d4f2d47dd0088a9573697ffae802ced7b79ee4a73fc69b784b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_linux_amd64.tar.gz"
      sha256 "ab1171e29334285f3d2477ea3cc0962b672c860356d763f6ec7c922f39273f92"
    end
    on_arm do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_linux_arm64.tar.gz"
      sha256 "b1ade02ea2157e3e8639d2fe56da1d89993d8aab0b216f800e352dc53d4ff2b8"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sfdc"]
  end

  caveats do
    "salesforce-cli has been installed."
    ""
    "To configure, run:"
    "  sfdc init"
    ""
    "You'll need a Connected App in Salesforce with OAuth 2.0 enabled."
  end

  # No zap stanza required
end
