# This file was generated by GoReleaser. DO NOT EDIT.
cask "salesforce-cli" do
  name "salesforce-cli"
  desc "Command-line interface for Salesforce"
  homepage "https://github.com/open-cli-collective/salesforce-cli"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sfdc"

  on_macos do
    on_intel do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_darwin_amd64.tar.gz"
      sha256 "779c8c764509caae89a58e84935a1ffe53837dc5db5a01f06ccc57549b4eaba6"
    end
    on_arm do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_darwin_arm64.tar.gz"
      sha256 "ea8ac732d5cb7eea06cfa77ea12e8185124c06fbfbd55f8e513ffcd40b3ded8b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_linux_amd64.tar.gz"
      sha256 "5f056f7dc5ebb1d2dd6624d20eef333f560181dbc6725e450a2b85b598867d35"
    end
    on_arm do
      url "https://github.com/open-cli-collective/salesforce-cli/releases/download/v#{version}/sfdc_#{version}_linux_arm64.tar.gz"
      sha256 "4b7788fd2fb07b976e3d935fa5e71d5868ffcc71a51d016787e9e15a3f5c1c29"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sfdc"]
  end

  caveats do
    "salesforce-cli has been installed."
    ""
    "To configure, run:"
    "  sfdc init"
    ""
    "You'll need a Connected App in Salesforce with OAuth 2.0 enabled."
  end

  # No zap stanza required
end
