# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-chat-cli" do
  version "3.2.67"

  on_macos do
    on_intel do
      sha256 "ef163273b47a2c8bd2d647a6ef5bbc9aeee37a91d878438ee0ea80890eb56b52"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a655a9471c6c792de7c85b22ec806c5effeb9d0a780656e2878d6deef56b46e"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "23650cf2098152358341c50070104e174567e9313582676d6d2cb3a8e9a930c7"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffeb3ee0e19a4cef0d324bc7185194a690372c7aac64908a0faa2e00257ef29a"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "slck"
  desc "Command-line interface for Slack"
  homepage "https://github.com/open-cli-collective/slack-chat-api"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slck"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slck"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure slck, run:
      slck init

    Tokens are stored in the OS keyring (Keychain on macOS,
    Credential Manager on Windows, Secret Service on Linux).
    They are never written to a plaintext file.
  EOS
end
