# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-chat-cli" do
  version "3.2.62"

  on_macos do
    on_intel do
      sha256 "9ab52ebed488f9e56694f84e1e57f52fdc86e6418eb4d7b02ba27054821e8859"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "480172c214b5f8b7fcf67d959620448ca2fa8351afccae43e3c2cfae603ff7ff"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cf123767fe8043ebe008d8e28c51fdc26d65812224eb18a645a7826bf2742496"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9ed58f36182cd2982b343debe357ed3acfb2f970a1d9137310d40e7a1260a61"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "slck"
  desc "Command-line interface for Slack"
  homepage "https://github.com/open-cli-collective/slack-chat-api"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slck"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slck"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure slck, run:
      slck init

    Tokens are stored in the OS keyring (Keychain on macOS,
    Credential Manager on Windows, Secret Service on Linux).
    They are never written to a plaintext file.
  EOS
end
