# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-chat-cli" do
  version "3.2.68"

  on_macos do
    on_intel do
      sha256 "9b2ef61add64a4e208b73bebd7485e98f0e0c413235dc86dd6c632eb80cfbcc9"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "06c1869fe3926f3617159bd9357a6a7273c202497e8056194a58520434958b81"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1aff1af565293b3d5f160f6100f625a8afb5092d75bf7bc5d3453d0be971d09a"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c3da93fe13e16dd92f4a520bef7ca0e412a6b37579009ed71a94c8ffb33c0879"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "slck"
  desc "Command-line interface for Slack"
  homepage "https://github.com/open-cli-collective/slack-chat-api"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slck"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slck"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure slck, run:
      slck init

    Tokens are stored in the OS keyring (Keychain on macOS,
    Credential Manager on Windows, Secret Service on Linux).
    They are never written to a plaintext file.
  EOS
end
