# This file was generated by GoReleaser. DO NOT EDIT.
cask "slck" do
  version "3.2.60"

  on_macos do
    on_intel do
      sha256 "630298fd85a5c7be64c27f43069ea751c18107dbb22f52e229eda9ab7e78443d"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd4f10c5bf4fa6789da351a30deeeb3336d553141656f8ab6a85a001926de3df"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac59152e39e6296fed99ed54777611f8642bd7716ef0de425b14779d049ae447"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "221b6931ce67b59fa6a60fc31749c5080879e3ff653fd38d0fa6912be1916045"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "slck"
  desc "Command-line interface for Slack"
  homepage "https://github.com/open-cli-collective/slack-chat-api"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slck"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slck"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure slck, run:
      slck init

    Tokens are stored in the OS keyring (Keychain on macOS,
    Credential Manager on Windows, Secret Service on Linux).
    They are never written to a plaintext file.
  EOS
end
