# This file was generated by GoReleaser. DO NOT EDIT.
cask "slck" do
  version "3.2.73"

  on_macos do
    on_arm do
      sha256 "dbd2ff0dec9245d0f0cc7c023588cfda687bb5b57024968435bc8dedd30b86dc"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f96369ff98aebe6e0b650cf8c317a6fecf164757c3e8939eef777721ba47f249"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6ca5604273904eb06750ab00ce06cae09646463f91610c5185ef394a41197d1e"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c18529241ed2976a749c18225b167758ca9fe950c1769fc512f970f616d1882c"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "slck"
  desc "Command-line interface for Slack"
  homepage "https://github.com/open-cli-collective/slack-chat-api"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slck"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/slck"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure slck, run:
      slck init

    Tokens are stored in the OS keyring (Keychain on macOS,
    Credential Manager on Windows, Secret Service on Linux).
    They are never written to a plaintext file.
  EOS
end
