# This file was generated by GoReleaser. DO NOT EDIT.
cask "slck" do
  version "3.2.70"

  on_macos do
    on_arm do
      sha256 "456cbb1ca6cbe014777eb1a22822ff888a1d89fd53bcd4a466b3b2039a781ce9"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d88b056134d395823facfcb9199efad381d7bf4d6f0a9692f9d82c409aa70e22"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3512e4b074016b4d13fb4cf7039d3c292335aed8202228e00e10346b4d18e612"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5eb31abe47ee53fa538be8165001090077b26994cc15692304a91b8f4c10ea73"
      url "https://github.com/open-cli-collective/slack-chat-api/releases/download/v#{version}/slck_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "slck"
  desc "Command-line interface for Slack"
  homepage "https://github.com/open-cli-collective/slack-chat-api"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slck"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slck"]
  end

  # No zap stanza required

  caveats <<~EOS
    To configure slck, run:
      slck init

    Tokens are stored in the OS keyring (Keychain on macOS,
    Credential Manager on Windows, Secret Service on Linux).
    They are never written to a plaintext file.
  EOS
end
