# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotify-cli" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "5bdc6b29012383c5a55f36d73042c752dc9495366c494012653e67e461cf84ef"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab2442d794dfb39404b74584fec2b99867d9d012e3899cbe5dca81c775df6e7c"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "17ae92f55848282997258f24e87d2e97127185266dc2af272e48324e2f442d98"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d250971fc883d52d05905eb4ac7e1ff6d52db41a7a62da930d54d29beba909c2"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "spotify-cli"
  desc "Spotify from the command line"
  homepage "https://github.com/open-cli-collective/spotify-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sptfy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sptfy"]
  end

  # No zap stanza required

  caveats <<~EOS
    Create a Spotify application, then run:
      sptfy init --client-id YOUR_CLIENT_ID

    OAuth credentials are stored in the configured credential backend.
  EOS
end
