# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotify-cli" do
  version "0.1.22"

  on_macos do
    on_arm do
      sha256 "41bfe5256dab174acaadada1936367d77004fe090316892bb8570cf10949af53"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3c3cec3bf05198ae28e09b0c53029fc5fbbdd78c323c918c9a1edc10b3c6b456"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "26b538514e7abf855ee00c4ef6f7eb8f2260c06ea92ed5882b161fb6ed7126be"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7612c22daebc9dc4e127e2f7f0a297d54913484a573e6b89bd8fe7689506edb"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_linux_amd64.tar.gz"
    end
  end

  name "spotify-cli"
  desc "Spotify from the command line"
  homepage "https://github.com/open-cli-collective/spotify-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sptfy"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/sptfy"]
  end

  # No zap stanza required

  caveats <<~EOS
    Create a Spotify application, then run:
      sptfy init --client-id YOUR_CLIENT_ID

    OAuth credentials are stored in the configured credential backend.
  EOS
end
