# This file was generated by GoReleaser. DO NOT EDIT.
cask "spotify-cli" do
  version "0.1.11"

  on_macos do
    on_intel do
      sha256 "adc4f7cd42dfd023c8a833487909c219bd59c015dae9d036fc04ec0d4656c74d"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc231be043bcb502e5fe489c5c77a4ec4c1ca6e527e8b08c50c6197e7f721c8a"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1dde11201ff443eb90b94fddea5e9fd3295af8fff093150114c6ff376edccd1e"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "78bef2c24f322b5a9bdab248fe8503c4c413ee0f9ded34e7222ce4f4c221602b"
      url "https://github.com/open-cli-collective/spotify-cli/releases/download/v#{version}/sptfy_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "spotify-cli"
  desc "Spotify from the command line"
  homepage "https://github.com/open-cli-collective/spotify-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sptfy"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sptfy"]
  end

  # No zap stanza required

  caveats <<~EOS
    Create a Spotify application, then run:
      sptfy init --client-id YOUR_CLIENT_ID

    OAuth credentials are stored in the configured credential backend.
  EOS
end
